apiVersion: v1
kind: Namespace
metadata:
  name: ai-gpu-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia-device-plugin
  namespace: flux-system
spec:
  interval: 1h
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: ai-gpu-system
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    runtimeClassName: nvidia
    nodeSelector:
      nvidia.com/gpu.present: 'true'
    affinity: {}
    failOnInitError: true
    gfd:
      enabled: false
    nfd:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi
    fullnameOverride: nvidia-device-plugin
  releaseName: nvidia-device-plugin
  postRenderers:
  - kustomize:
      patches:
      - target:
          group: apps
          version: v1
          kind: DaemonSet
          name: nvidia-device-plugin-mps-control-daemon
        patch: "$patch: delete\napiVersion: apps/v1\nkind: DaemonSet\nmetadata:\n\
          \  name: nvidia-device-plugin-mps-control-daemon\n  namespace: ai-gpu-system\n"
